# Generated by Django 3.2.6 on 2021-08-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Antes: ('clients', '0001_initial'),
        # Ajustado para refletir o novo app 'core'
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='core.address'),
        ),
    ]
